version: "3.7"
services:
  rs-sftp:
    build: .
    environment:
      AZURE_BLOB_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://sftp-Azurite:10000/devstoreaccount1;QueueEndpoint=http://sftp-Azurite:10001/devstoreaccount1; # pragma: allowlist secret
      ENV: local
      # Uncomment the line below to call local report stream. Otherwise we'll use a mock response
      REPORT_STREAM_URL_PREFIX: http://host.docker.internal:7071
      FLEXION_PRIVATE_KEY_NAME: trusted-intermediary-private-key-local #pragma: allowlist secret
      FLEXION_CLIENT_NAME: flexion.simulated-hospital
    volumes:
      # map to Azurite data objects to the build directory
      - ./localdata/reportstream:/localdata
      - ./mock_credentials:/mock_credentials
    ports:
      - "8081:8080" # default api endpoint port
    platform: linux/amd64
    depends_on:
      sftp-Azurite:
        condition: service_started
      azure-cli:
        condition: service_completed_successfully
    networks:
      - sftp

  sftp-Azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    # uncomment the line below to skip x-ms-version checks
    # command: azurite --skipApiVersionCheck --blobHost 0.0.0.0 --queueHost 0.0.0.0
    volumes:
      # map to Azurite data objects to the build directory
      - ./localdata/azurite:/data
    ports:
      - "12000:10000"
      - "12001:10001"
      - "12002:10002"
    networks:
      - sftp

  azure-cli:
    image: mcr.microsoft.com/azure-cli
    volumes:
      - ./mock_data:/mock_data
    command:
      - /bin/sh
      - -c
      - |
        az storage container create -n sftp
        az storage blob upload --overwrite --account-name devstoreaccount1 --container-name sftp --name order_message.hl7 --file mock_data/order_message.hl7
        az storage queue create -n flexion.simulated-hospital-local
    environment:
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://sftp-Azurite:10000/devstoreaccount1;QueueEndpoint=http://sftp-Azurite:10001/devstoreaccount1; # pragma: allowlist secret
    networks:
      - sftp
    depends_on:
      - sftp-Azurite


networks:
  sftp:
