name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./src/go.mod
          cache-dependency-path: ./src/go.sum

      - name: Run unit tests
        run: make unitTestsWithCoverageThreshold

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # helps with Sonar scanning

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./src/go.mod
          cache-dependency-path: ./src/go.sum

      - name: Vet
        run: make vet

      - name: Go Fmt
        run: make formatCheck

      - name: Terraform Formatting
        working-directory: operations
        run: terraform fmt -recursive -check

      - name: Unit Tests with Code Coverage
        run: make unitTests

      - name: Sonar
        uses: sonarsource/sonarcloud-github-action@v4.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: src
          args: >
            -Dsonar.projectKey=CDCgov_reportstream-sftp-ingestion
            -Dsonar.organization=cdcgov
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*_test.go
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.go.coverage.reportPaths=coverage.out

  securityScanAnalyze:
    name: CodeQL Security Scan
    uses: ./.github/workflows/codeql_reusable.yml

  docker-build-test:
    name: Docker Build Test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./src/go.mod
          cache-dependency-path: ./src/go.sum

      - name: Build Image
        run: make dockerBuild

      # Not using the Makefile because it includes `-i` which bombs out in GitHub Actions.
      - name: Run Container
        run: docker run -d -t reportstream-sftp-ingestion
