name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: go test ./...

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:

      - name: Vet
        run: go vet ./

      - name: Go Fmt
        run: gofmt -l ./ && test -z "$(gofmt -l ./)"
