name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: make unitTests

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Vet
        run: make vet

      - name: Go Fmt
        run: make formatCheck

  securityScanAnalyze:
    name: CodeQL Security Scan
    uses: ./.github/workflows/codeql_reusable.yml

  docker-build-test:
    name: Docker Build Test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build Image
        run: make dockerBuild

      # Not using the Makefile because it includes `-i` which bombs out in GitHub Actions.
      - name: Run Container
        run: docker run -t reportstream-sftp-ingestion
