name: Deploy to Production Environment

on:
  release:
    types:
      - published

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  terraform-deploy:
    name: Production Infrastructure Deploy
    needs: ci
    uses: ./.github/workflows/terraform-deploy_reusable.yml
    with:
      ENVIRONMENT: prd
      TERRAFORM_DIRECTORY: operations/environments/prd
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CDC_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_CDC_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_CDC_DMZ_C1_SUBSCRIPTION_ID }}
      TERRAFORM_APPLY_PARAMETERS: -var="alert_slack_email=${{ secrets.ALERT_SLACK_EMAIL }}"

  prd-deploy:
    name: Production Deploy Application Deploy
    needs: terraform-deploy
    uses: ./.github/workflows/deploy_reusable.yml
    with:
      ENVIRONMENT: prd
      REPO: report-stream-sftp-ingest
      APP: ${{ needs.terraform-deploy.outputs.APP }}
      REGISTRY: ${{ needs.terraform-deploy.outputs.REGISTRY }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CDC_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_CDC_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_CDC_DMZ_C1_SUBSCRIPTION_ID }}
