name: SonarQube Analysis

on:
  push:  # Trigger on push to any branch
  pull_request:  # Trigger on pull request to any branch

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./src/go.mod
      - name: set up java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: Install SonarQube Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner.zip -d $HOME
          echo "$HOME/sonar-scanner-4.6.2.2472-linux/bin" >> $GITHUB_PATH

#      - name: Run tests and generate coverage
#        run: |
#          cd src
#          go test -v ./... -coverprofile=coverage.out
#          cat coverage.out
#          go tool cover -func=coverage.out

      - name: SonarQube Scan
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Corretto_jdk/17.0.11-9.1/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Corretto_jdk/17.0.11-9.1/x64
          SONAR_TOKEN: ${{ secrets.SFTP_INGESTION_SONAR_TOKEN }}
        run: |
          java -version
          cd src
          sonar-scanner \
            -Dsonar.projectKey=CDCgov_reportstream-sftp-ingestion \
            -Dsonar.organization=cdcgov \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.sources=. \
#            -Dsonar.tests=. \
#            -Dsonar.go.coverage.reportPaths=coverage.out
      
